appName:            DepthEstimation
modelName:          resnet-unet-cameraintrinsics

Optimizer:
    Type:           AdamW
    LR:             1e-4
    WeightDecay:    0.05

Scheduler:
    Type:           CosineAnnealingLR
    NumEpochs:      20

DataLoader:
    Path:           /scratch/mp6021/Monodepth2/data/KITTI
    SplitsType:     eigen_zhou
    BatchSize:      24
    NumWorkers:     14

Logger:
    Path:           ./logs

Trainer:
    Epochs:         20
    ModelSavePath:  ./trained_models

Model:
    Arch:           UNET
    Encoder:        EncoderModelResNet
    EncoderTrain:   True
    DepthDecoder:   DepthDecoderModel
    ESPCN:          False
    PoseEncoder:    Shared
    PoseDecoder:    PoseDecoderModel
    Automasking:    True
    K_Trainable:    True
    Additional:     CameraIntrinsics
    
CameraIntrinsics:
    bottleneck_channels:    6
    h:                      self.height//8
    w:                      self.width//8