appName:            DepthEstimation
modelName:          resnet-unetplusplus

Optimizer:
    Type:           AdamW
    LR:             1e-4
    WeightDecay:    0.05

Scheduler:
    Type:           CosineAnnealingLR
    NumEpochs:      20

DataLoader:
    Path:           /scratch/mp6021/Monodepth2/data/KITTI
    SplitsType:     eigen_zhou
    BatchSize:      12
    NumWorkers:     14

Logger:
    Path:           ./logs

Trainer:
    Epochs:         20
    ModelSavePath:  ./trained_models

Model:
    Arch:           UNETPlusPlus
    Encoder:        EncoderModelResNet
    EncoderTrain:   True
    DepthDecoder:   DepthDecoderModel
    ESPCN:          True
    PoseEncoder:    Shared
    PoseDecoder:    PoseDecoderModel
    Automasking:    True
    K_Trainable:    False
    Additional:     False